runtime: nodejs20
service: shapefile-bigquery

env_variables:
  NODE_ENV: production
  PORT: 8080 # App Engine will set the PORT environment variable,
              # but it's good practice if your app listens to process.env.PORT || 8080

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

handlers:
- url: /api/.*
  script: auto
  secure: always

- url: /.*
  static_files: client/dist/\1
  upload: client/dist/(.*) # This regex ensures all files in client/dist are uploaded
  secure: always
